GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET http://localhost:8008/lxj/allEmp?pageNo=1?size=1
Accept: application/json


###
GET http://localhost:8008/lxj/allRoleMy
Accept: application/json

###
